### ISSUE TITLE
Search manager returning max of 10 results

### ISSUE THREAD

**Issue by mathiasvanh** [coveooss/platform-sdk#4]
Question:
I'm currently implementing a search functionality using the searchmanager. I initlize the class like this:
` using var client = GetPlatformClient();
            return client.SearchManager.Search(new QueryParameters
            {
                Query = query,
                Pipeline = Settings.Pipeline,
                ViewAllContent = true
            }, cancellationToken);
`
But this is only returning a max result of 10 items.

Thing I've tried:
- Looked for a property in the Query Parameters class
- Set the page size on the CoveoPlatformConfig after initlizing it
- Add 'numberOfResults' in the query parameter

When I do the same request via postman I see more results, so I don't think the issue is with the settings on the Coveo platform. 

Can you please give more insight on how I should tackle this?

**Comment by ldblanchet** [comment]
Try setting the PageSize in the config before creating the CoveoPlatformClient. The default page size is a 100, so if you have more than 100, you should get 100?
One thing to note is that the SearchManager does not support paginated queries, so if your results do not fit on a single page, it's not supported right now. How many results are you expecting?
What was the postman query you performed that worked?
