### ISSUE TITLE
push content not received by push source

### ISSUE THREAD

**Issue by gabstp** [coveooss/platform-sdk#7]
Hi! I made a simple script to push the content in a folder to a push a source using the examples provided here : https://github.com/coveooss/platform-sdk . It works perfeclty for the first few thousands documents (45-80k) but at some point, my script continues to log that it pushes content, but the content stops being added to the source and nothing gets logged in the log browser of the admin console. On my side, the call to the  AddOrUpdateDocuments method throws no exception.

Is there a way to know what happens or when it happens to fix it, or at least stop the process and restart it later?

**Comment by gabstp** [comment]
xvqqcayhvnrlqju6hfqfcokfmi, do you need the organization id too?

**Comment by ClaudineL** [comment]
Yes please.

**Comment by ClaudineL** [comment]
If you could link us directly to your admin UI page it would help a lot too.

**Comment by gabstp** [comment]
https://platform-ca.cloud.coveo.com/admin/#/centredaccslinformationjuridiquecaijnonproduction2yq5emeho/content/sources

**Comment by ClaudineL** [comment]
It looks like only 5K documents are getting indexed, is it possible to look at your script?

**Comment by gabstp** [comment]
I removed what was not necessary. That is the version with which I try to push the whole content of a directory. I also tried with a recursive function that takes chunks of 10k files, but I had the same result.

[script.txt](https://github.com/coveooss/platform-sdk/files/11558981/script.txt)

**Comment by gabstp** [comment]
I will start a new indexing operation while logging in debug level and I will update you on the result. The log for the push to the canlii source has been overwritten (will fix it for the next push) but I had nothing after 5:07:57 PM on may 23, when the push stopped working. Logs were normal before that.

**Comment by gabstp** [comment]
I made a few push today, all went well until the last. I pushed 6 738 files, but only 3 640 seem to have made it. The number of files in the canlii source should be 77 429. I still have no error in my log and I see that the AddOrUpdateDocuments method of the sdk was called with 6 738 items at 15:30:59.

**Comment by ClaudineL** [comment]
We really need the logs with debug logging turned on to see what's happening inside the platformSDK, it's not really possible for me to investigate any further without this.

**Comment by jmorissette** [comment]
Just to be sure, you have some batch that failed on your organisation because of their size. If you look into the log browser there is the following : 

```
The large file for add/update/delete with id '{some file id}' has a size of '267367668' bytes and the maximum allowed by the license is '256000000' bytes. It will not be processed.
```

**Comment by gabstp** [comment]
DId the failure happen today? From what I see all log entries from today are completed.

**Comment by ClaudineL** [comment]
Yes, I can see those errors today, and I saw them on the operations from May 23rd as well: 
![image](https://github.com/coveooss/platform-sdk/assets/50966943/2269c8ce-893a-4f13-baa7-de2550d8a5f1)

**Comment by ClaudineL** [comment]
I would suggest trying to use smaller batches like 100-200 documents at a time, it seems the license uses `256,000,000` as a size limit but our code uses `267,386,880` as a limit to put in one batch. With smaller batches there might be less of a chance to hit this sweet spot.
