### ISSUE TITLE
Making partial item updates to existing documents? 

### ISSUE THREAD

**Issue by kknd4eva** [coveooss/platform-sdk#9]
I can't find a method or service within the SDK to achieve the following steps? (What am I missing?)

1. Create a file container in S3
2. Upload to the file container
3. Push the fieldValueReplace to the source and document specified. 

Basically, the code equivalent of: 

```
{
  "partialUpdate": [
    {
      "documentId": "https://sapcommerce/product/p/40035",
      "operator": "fieldValueReplace",
      "field": "9991_9993",
      "value": "true"
    }
  ]
}
```

**Comment by ldblanchet** [comment]
Unfortunately, the PlatformSDK does not support partial updates. For large files, the SDK takes care of requesting the S3 container.
